### ISSUE TITLE
[HOLD react-native-x-maps Issue #14] Setup TypeScript for `react-native-x-draggable-list`

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/react-native-x-draggable-list#4]
- [ ] Init `tsconfig.json`
- [ ] Install and configure TypeScript ESLint plugins
- [ ] Setup CL for type checking

**Comment by neil-marcellini** [comment]
Let's also close this since we [decided](https://expensify.slack.com/archives/C03TQ48KC/p1693248554091449?thread_ts=1693240753.590539&cid=C03TQ48KC) to remove these separate libraries.
